[package]
name = "complex_numbers"
version = "0.1.3"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
round = "0.1.2"
